name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up our JDK environment
      uses: actions/setup-java@v4.4.0
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4.2.2
      with:
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
    - name: Build with Gradle
      run: ./gradlew testDebugUnitTest
