name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.2
    - name: Set up our JDK environment
      uses: actions/setup-java@v3.4.1
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.2.5
      with:
        arguments: build
